### ISSUE TITLE
Output of task call is not valid

### ISSUE THREAD

**Issue by NicolasMahe** [liteflow-services/webhook#4]
Related to https://github.com/mesg-foundation/core/issues/800

The output success of the task call is not valid:
https://github.com/mesg-foundation/service-webhook/blob/223ea4e268726081fe43e156171b92c3a4087118/mesg.yml#L34-L36

The core rejects when the result is emitted with error:
```
error: 'invalid output data error: json: cannot unmarshal string into Go value of type map[string]interface {}' }
```

The command `service validate` should reject to not have an data definition like this.

The proper definition is:

```yaml
result: 
  description: "Result of the call the returns the list of the data from the API call result" 
  data:
    data:
      type: Object
```
